import mysql.connector


def get_connection():
    return mysql.connector.connect(
        host="localhost",
        user="root",
        password="william",
        database="lms_database"
    )


fake_courses = {
    "Computer Science": "Study of computation, algorithms, and programming languages.",
    "Biology": "Exploration of living organisms and biological systems.",
    "Chemistry": "Study of matter, reactions, and molecular structures.",
    "Physics": "Investigation of motion, energy, and fundamental forces.",
    "Mathematics": "Analysis of numbers, equations, and abstract structures.",
    "Psychology": "Study of human behavior and mental processes.",
    "History": "Examination of past events and civilizations.",
    "English Literature": "Analysis of written works and literary traditions.",
    "Economics": "Study of production, consumption, and resource allocation.",
    "Business Administration": "Management of organizations and business operations.",
    "Engineering": "Application of science and math to build structures and systems.",
    "Nursing": "Healthcare and patient care training.",
    "Law": "Study of legal systems, rights, and justice.",
    "Architecture": "Design and planning of buildings and structures.",
    "Environmental Science": "Study of ecosystems and environmental challenges.",
    "Sociology": "Analysis of society, culture, and human interactions.",
    "Art History": "Study of artistic movements and cultural expressions.",
    "Political Science": "Examination of government systems and politics.",
    "Music Theory": "Study of musical composition and sound principles.",
    "Philosophy": "Inquiry into fundamental questions of existence and knowledge.",
    "Computer Engineering": "Design and development of computer hardware and systems.",
    "Data Science": "Analysis of large datasets and extraction of insights.",
    "Cybersecurity": "Protection of computer systems and networks from threats.",
    "Artificial Intelligence": "Development of intelligent machines and algorithms.",
    "Graphic Design": "Visual communication through images and layouts.",
    "Marketing": "Promotion and selling of products and services.",
    "Astronomy": "Study of celestial objects and the universe.",
    "Geology": "Investigation of rocks, minerals, and Earth's structure.",
    "Anthropology": "Study of human cultures and civilizations.",
    "Statistics": "Collection and analysis of data and probability.",
    "Database Design": "Creation and management of data storage systems.",
    "Web Development": "Building and maintaining websites and web applications.",
    "Mobile App Development": "Creating applications for smartphones and tablets.",
    "Software Engineering": "Systematic approach to designing and building software.",
    "Computer Networks": "Study of network protocols and communication systems.",
    "Operating Systems": "Management of hardware resources and system operations.",
    "Machine Learning": "Algorithms that enable computers to learn from data.",
    "Natural Language Processing": "Processing and understanding human language.",
    "Computer Graphics": "Creation and manipulation of visual images with computers.",
    "Cloud Computing": "Delivery of computing services over the internet.",
    "Civil Engineering": "Design and construction of infrastructure and buildings.",
    "Mechanical Engineering": "Design of mechanical systems and machines.",
    "Electrical Engineering": "Study of electrical systems and power generation.",
    "Chemical Engineering": "Application of chemistry to industrial processes.",
    "Aeronautical Engineering": "Design and development of aircraft and aerospace systems.",
    "Structural Analysis": "Evaluation of building and bridge structural integrity.",
    "Thermodynamics": "Study of heat, energy, and temperature relationships.",
    "Fluid Mechanics": "Study of liquids and gases in motion.",
    "Finance": "Management of money, investments, and financial planning.",
    "Accounting": "Recording, reporting, and analysis of financial transactions.",
    "Human Resources Management": "Recruitment, training, and employee relations.",
    "Supply Chain Management": "Coordination of product distribution and logistics.",
    "International Business": "Commerce and operations across national borders.",
    "Entrepreneurship": "Creation and management of new business ventures.",
    "Business Analytics": "Data-driven decision making for organizations.",
    "Organizational Behavior": "Study of human behavior within organizations.",
    "Medical Surgery": "Operative procedures and surgical techniques.",
    "Pharmacology": "Study of drugs and their effects on organisms.",
    "Public Health": "Community health promotion and disease prevention.",
    "Pathology": "Study of disease causes and effects.",
    "Radiology": "Medical imaging and diagnostic techniques.",
    "Cardiology": "Study and treatment of heart diseases.",
    "Pediatrics": "Medical care of infants and children.",
    "Psychiatry": "Treatment of mental health disorders.",
    "Microbiology": "Study of microscopic organisms and their effects.",
    "Genetics": "Study of heredity and genetic traits.",
    "Molecular Biology": "Study of molecules and cellular processes.",
    "Ecology": "Study of organisms and their environments.",
    "Organic Chemistry": "Study of carbon-containing compounds.",
    "Astrophysics": "Study of stars, galaxies, and cosmic phenomena.",
    "Quantum Mechanics": "Study of atomic and subatomic particles.",
    "Nuclear Physics": "Study of atomic nuclei and radioactivity.",
    "Medieval Studies": "Study of Europe in the Middle Ages.",
    "Classical Studies": "Study of ancient Greece and Rome.",
    "Renaissance Studies": "Study of the European Renaissance period.",
    "American History": "Study of United States history and development.",
    "Asian Studies": "Study of Asian cultures and societies.",
    "Comparative Literature": "Study of literature across different cultures.",
    "Creative Writing": "Development of fiction, poetry, and narrative skills.",
    "Linguistics": "Study of language structure and communication.",
    "Gender Studies": "Analysis of gender roles and identities.",
    "Cultural Studies": "Examination of culture, media, and society.",
    "Painting": "Study and practice of painting techniques.",
    "Sculpture": "Creation of three-dimensional artworks.",
    "Photography": "Capturing and manipulating photographic images.",
    "Film Studies": "Analysis of cinema and filmmaking.",
    "Performance Art": "Artistic expression through live performance.",
    "Digital Art": "Creation of art using digital technologies.",
    "Typography": "Design and use of typefaces and fonts.",
    "Fine Arts": "Study of visual art forms and techniques.",
    "Classical Composition": "Creation of orchestral and chamber music.",
    "Jazz Improvisation": "Spontaneous creation of jazz music.",
    "Music Production": "Recording, mixing, and mastering of audio.",
    "Sound Engineering": "Technical aspects of audio and sound design.",
    "Ethnomusicology": "Study of music from different cultures.",
    "Conducting": "Leadership and direction of musical ensembles.",
    "Musicology": "Historical and analytical study of music.",
    "Elementary Education": "Teaching methods for primary school students.",
    "Secondary Education": "Teaching methods for high school students.",
    "Special Education": "Teaching methods for students with disabilities.",
    "Educational Psychology": "Application of psychology to teaching and learning.",
    "Curriculum Development": "Design of educational programs and course content.",
}


